patch(container): sync with upstream (#1)
crazy-max/docker-alpine-s6 pull request #53
Opened 2022-07-06 01:40 UTC by sambacha

2022-07-06 20:10 UTC, crazy-max requested changes

2022-07-07 11:43 UTC, sambacha commented
thanks, I choose the ref with the comment update. The one you suggested is the actual commit [https://github.com/just-containers/s6-overlay/commit/fe6dec976ea1be2cdf22851dbdb0104371415524](https://github.com/just-containers/s6-overlay/commit/fe6dec976ea1be2cdf22851dbdb0104371415524)

I should have just picked it from the [`VERSIONS` file](https://github.com/just-containers/s6-overlay/blob/v3.1.1.2/conf/versions) - much obliged.

Thanks

2022-07-11 21:22 UTC, crazy-max commented
@sambacha I pick the one from the release page: https://github.com/just-containers/s6-overlay/releases/tag/v3.1.1.2

![image](https://user-images.githubusercontent.com/1951866/178360611-2484506a-d9ae-44d0-b4ab-7b0eae09aad2.png)

2022-07-11 21:22 UTC, crazy-max approved these changes
LGTM

2022-07-11 21:23 UTC, merged